### ISSUE TITLE
Don't expose the multiple city functionality... yet

### ISSUE THREAD

**Issue by NigelKibodeaux** [codeforanchorage/collective-development#11]
I'm thinking that we want to simplify the interface since we're only starting with Anchorage. What do others think?

Hopefully this is just a config setting.

**Comment by muskox** [comment]
I think that sounds reasonable, keep the scope small to begin with.

**Comment by thermokarst** [comment]
Sounds good to me. The locations fall under 'Schools'. Seems like the easiest way is to only create the default school (www) when we initialize the DB.
