### ISSUE TITLE
Outputting people's names

### ISSUE THREAD

**Issue by NigelKibodeaux** [codeforanchorage/collective-development#14]
We should be careful about printing the list of people who have said they are interested in the class. They might not want their name/interest to be public.

**Comment by NigelKibodeaux** [comment]
Possible solution: just describe bette what display name is.

Possible solution: tell them that username is public and full name is not

Possible solution: just don't display interested users to the public

**Comment by brendanbabb** [comment]
Some people might want to avoid taking a class with someone. The Display name can keep their privacy and also let them see if a friend is taking the class or avoid someone. Provide better definition of Display Name.

**Comment by brendanbabb** [comment]
Displaying Display name. Brent completed this.
