### ISSUE TITLE
Class time availability

### ISSUE THREAD

**Issue by NigelKibodeaux** [codeforanchorage/collective-development#15]
It might be good to collect the times that people are available to take a class.

For example, if 15 people are interested in the class, it may have reached critical mass. However, maybe only 5 can take a class during the morning and 5 can only attend afternoons and the other 5 are looking for a class after work. This could prevent the class from getting enough attendees to happen. Same thing applies for days of the week.

I don't know the best way to address this but maybe a day/time whitelist or blacklist per user makes sense.

**Comment by brendanbabb** [comment]
A suggestion for possible scheduling of classes by knowing the rough availability of when prospective students would be available.

**Comment by brendanbabb** [comment]
Rough availability added by Brent
