### ISSUE TITLE
Allow attaching a user to a class as a teacher

### ISSUE THREAD

**Issue by NigelKibodeaux** [codeforanchorage/collective-development#16]
The teacher should also be able to specify a time or times when they are available to teach the class.

Teachers should be able to be added after the fact also.

We should allow users to volunteer to teach a class somehow.

**Comment by brendanbabb** [comment]
Should we show the teacher of a class so people can use that info to decide on taking the class? This would only be known after the a teacher was assigned.

**Comment by brendanbabb** [comment]
A person can say they are interested in teaching a proposal. A field for teacher is included in classes.
