### ISSUE TITLE
When you "Propose a Class!" it asks which school

### ISSUE THREAD

**Issue by hansthompson** [codeforanchorage/collective-development#20]
When you Propose a Class it asks which school. No schools listed. I don't see anything in the propose a class area when I'm logged in.

**Comment by brendanbabb** [comment]
Is this because we don't have schools in the database?

**Comment by bgonzales-pango** [comment]
After checking the database, the only school in there is "www".

**Comment by brendanbabb** [comment]
What happens if you add another school. The edit form for a proposal exists, it is just not showing it yet.

**Comment by brendanbabb** [comment]
What happens if you add another school. The edit form for a proposal exists, it is just not showing it yet.

**Comment by brendanbabb** [comment]
Butter fingers on plane and phone. Reopening

**Comment by brendanbabb** [comment]
Brent set it up so you can propose a class.
