### ISSUE TITLE
Do you want Vagrant support?

### ISSUE THREAD

**Issue by muskox** [codeforanchorage/collective-development#25]
I have this working in an ubuntu VM. I could port this to vagrant if anyone would use it. Any takers?

**Comment by thermokarst** [comment]
I think setting up an alternative to the Docker stuff if worthwhile --- thanks!

**Comment by tescher** [comment]
I'll probably just set up an Ubuntu VM on my machine and install from the notes so I can better understand how it's all put together. Do you still want a public site out somewhere so Meg and others can play, demo, or set up content? I could probably host it on one of my Webfaction machines for a while.

**Comment by thermokarst** [comment]
@tescher: Just to clarify, a vagrant configuration would do just that --- set up and provision a VM automatically. Certainly is worth looking into on your own though.
Regarding hosting, thanks, but I think we should stay with AWS --- we have financial support on that platform, and the aim is to allow access to all devs on the project.

**Comment by brendanbabb** [comment]
I agree if we can do it on AWS, Code for America will pay for it all.
Digital Ocean to a lesser extent, so AWS would be good if doable.

We would like a test version up that we could fix bugs via Github and
redeploy to test and shortly have a site where we can do a test run with
5-8 people offering events/classes.

Brendan

**Comment by muskox** [comment]
Hey All,
I started a Vagrantfile. I'll make a PR with the newest README and others can test it before pushing into master. @brendanbabb My plan is to have dev, stage, and prod in AWS. That will be separate from Vagrant so I'll close this issue because this was about Vagrant support.
